"""init

Revision ID: 8080af197cf6
Revises: 79d1344fdd8d
Create Date: 2025-11-21 14:44:24.099558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8080af197cf6'
down_revision: Union[str, Sequence[str], None] = '79d1344fdd8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_user_id_key'), 'cart', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('cart_user_id_key'), 'cart', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
